"""Add overall_assessment

Revision ID: 637d3950f5b5
Revises: 715d056cdd1f
Create Date: 2026-06-13 15:13:35.714438
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers
revision: str = '637d3950f5b5'
down_revision: Union[str, None] = '715d056cdd1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('overall_assessment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'overall_assessment')
    # ### end Alembic commands ###
