"""Add strengths and candidate_potential to Evaluation

Revision ID: 715d056cdd1f
Revises: 002_session_persist
Create Date: 2026-06-13 14:33:19.211934
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers
revision: str = '715d056cdd1f'
down_revision: Union[str, None] = '002_session_persist'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('strengths', sa.JSON(), nullable=True))
    op.add_column('evaluations', sa.Column('candidate_potential', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'candidate_potential')
    op.drop_column('evaluations', 'strengths')
    # ### end Alembic commands ###
